### ISSUE TITLE
Can you make a country called Global?

### ISSUE THREAD

**Issue by bhbmaster** [pomber/covid19#102]
Can you make a "country" called "Global" or "Total" which is just the sum of all of the countries?
its up to you
I personally do it my self in my tool:
https://github.com/bhbmaster/covid19/blob/master/README.md
It will benefit all of the tools that use yours as users will be able to see global.
Curious what the global logarithmic best fit is (some of your json users provide this metric)

**Comment by pomber** [comment]
Hi. Adding that would break some of the JSON's consumers. I prefer not to add it.

**Comment by charrismatic** [comment]
@bhbmaster I think add computed valued to datasets is a bad practice, especially since there is no actuallly country named "global" in real life. It  opens you up for errors and extra work down the road. Maybe a utility script would be more appropriate, you could set it up to run with Git Hooks or GitHub actions and you would still have our summary data without affecting the  quality of the source dataset.

**Comment by bhbmaster** [comment]
I understand and very good points. Thank you
