### ISSUE TITLE
Can we add latest.json

### ISSUE THREAD

**Issue by vixalien** [pomber/covid19#210]
Obviously, this would show latest data in this form:

```json
"Afganistan": {
  "deaths": 000,
  "recovered":000,
  "cases": 000,
  "updated_at": "2020_12_5#4:26_AM#EET Something compatible with new Date() or generally ISO "
}
```
It would be fancy to add this:
```json
{
  "new_deaths": 000,
  "new_cases": 000,
  "new_recovered": 000,
}
```
This is because fetching the whole `time..json` is crudesome, something smaller would be nice.

**Comment by dprojects** [comment]
You can convert data to get timestamp but probably there is no data with correct time? Maybe for US where is so many confirmed cases each hour, for other countries government posts 3 or 1 time daily the covid-19 update.  

Some of new_ values would be below zero. 
(see issue here: https://github.com/CSSEGISandData/COVID-19/issues/2502).

It would be nice to have entry "tests made already" so it would be easy to calculate how many people might be infected in such place, e.g. if you made 100 tests and 30 people have positive result, you can assume that 30% of all people are infected (for sure this is how it goes because there are much more people infected or recovered than officially known).
