### ISSUE TITLE
Data Update

### ISSUE THREAD

**Issue by maisonml** [pomber/covid19#24]
The data isn't updated today. At what time do you update 20th March's data? It's 8 PM EST. Please let me know if you ll be updating it everyday.

**Comment by Maanuj-Vora** [comment]
The data is being updated thru Github Actions, if you click on the Actions tab on the top, it shows that it has ran, and the data gathered more depends on the repository of which the data is coming from, [.](https://github.com/CSSEGISandData/COVID-19). As for the .json file not updating, I am not sure, it may be due to the same data being already present, so it doesn't need to update again. Need to get confirmation on that though.

**Comment by pomber** [comment]
> As for the .json file not updating, I am not sure, it may be due to the same data being already present, so it doesn't need to update again. Need to get confirmation on that though.

That's right, the json is only updated when something changed in the source. 


> At what time do you update 20th March's data?

It's usually updated around 5am UTC time, but it depends on the changes from the source repo.

**Comment by Mawreck** [comment]
I just recently created an app out of boredom that shows my countrys corona virus infected status. Just wanted to give you headsup, nice job @pomber ! Hopefully the data will refresh. I will try to get a public domain tomorrow.

**Comment by Maanuj-Vora** [comment]
Hi, so I have created a repository similar to this one, [Repo](https://github.com/Maanuj-Vora/Bing-COVID-19-Current-Data), which takes the data from Bing COVID-19 Tracker, which sources other places, and saves it into a json object as well. As the tracker only gives current data, I don’t have the previous data in the format, but I have started archiving the data from today. So, if you have time, please check it out and help provide me some feedback, it would be very much appreciated!

**Comment by zbraniecki** [comment]
@Maanuj-Vora I really like your data model. It has regions! It'd be awesome to have this data backtracked to at least 18th of Jan.

**Comment by Maanuj-Vora** [comment]
Yep, it does have regions! As for the data backtrack, I’ll try to see if I can do it, but I don’t think it’s possible with my knowledge. But hey, you never know. Thank you for your feedback!

**Comment by Mauricevb** [comment]
> > As for the .json file not updating, I am not sure, it may be due to the same data being already present, so it doesn't need to update again. Need to get confirmation on that though.
> 
> That's right, the json is only updated when something changed in the source.
> 
> > At what time do you update 20th March's data?
> 
> It's usually updated around 5am UTC time, but it depends on the changes from the source repo.

Is it possible to increase the update frequency to twice a day?

**Comment by Maanuj-Vora** [comment]
The source [repo](https://github.com/CSSEGISandData/COVID-19) is where you should ask this question, but the most likely answer is going to be no due to the sheer amount of data they are going through, and having problems with data right now, which you can take a look in the issues section of that repo.

**Comment by Mawreck** [comment]
@pomber 
my site is up on -> https://covid19eesti.ee/

using your data as fetch, ty bro!
